name: Deploy Monitoring

on:
  push:
    branches: [ "develop-temp" ]
    paths:
      - '.github/workflows/cd-monitoring.yml'
      - '../../../lieklion14th-homepage-be/docker/sieon/monitoring/docker-compose-monitoring.yml'
      - '../../../lieklion14th-homepage-be/docker/sieon/monitoring/grafana/**'
      - '../../../lieklion14th-homepage-be/docker/sieon/monitoring/prometheus/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy monitoring files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.MONITORING_SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.MONITORING_SSH_PRIVATE_KEY }}
          source: "docker/monitoring/docker-compose-monitoring.yml,docker/monitoring/prometheus/,docker/monitoring/grafana/"
          target: "~/app"

      - name: Deploy Monitoring Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MONITORING_SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.MONITORING_SSH_PRIVATE_KEY }}
          script: |
            echo "🟢 [MONITORING] festival-monitoring-network 생성"
            docker network inspect festival-monitoring-network >/dev/null 2>&1 \
              || docker network create festival-monitoring-network

            cd ~/app/docker/monitoring

            echo "🟢 [MONITORING] 모니터링 스택 재배포"
            docker compose -f docker-compose-monitoring.yml down
            docker compose -f docker-compose-monitoring.yml pull
            docker compose -f docker-compose-monitoring.yml up -d

            echo "✅ [MONITORING] 배포 완료"